"""Protocols exposed to plugin authors without host implementations."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RegistrationPort(Protocol):
    def tool(self, entry: Any) -> None: ...
    def skill(self, entry: Any) -> None: ...
    def skills(self, relative_path: str | Path = "skills") -> int: ...
    def workflow(self, definition: Any) -> None: ...
    def platform(self, entry: Any) -> None: ...
    def mcp_server(self, config: Any) -> None: ...
    def mcp(self, relative_path: str | Path = "mcp.yaml") -> int: ...
    def hook(self, event: Any, callback: Any, priority: int = 100, **kwargs: Any) -> None: ...
    def command(self, entry: Any) -> None: ...
    def memory_provider(self, *, name: str, factory: Any, validator: Any) -> None: ...
    def active(self, *, run: Any, resources: Any = None, **kwargs: Any) -> None: ...


@runtime_checkable
class PluginRuntimeContext(Protocol):
    plugin_key: str
    generation_id: str
    runtime_instance_id: str
    register: RegistrationPort

    @property
    def config(self) -> Any: ...
    @property
    def root(self) -> Path | None: ...
    @property
    def runtime(self) -> Any: ...
    @property
    def resources(self) -> Any: ...
    @property
    def storage(self) -> Any: ...
    @property
    def tasks(self) -> Any: ...
    @property
    def invocation(self) -> Any: ...
    def parse_config(self, model_type: Any) -> Any: ...
    def get_env(self, name: str, default: str = "") -> str: ...
    def resolve_path(self, relative_path: str | Path) -> Path: ...
